### ISSUE TITLE
Dynamics 365 Business Central Usage v357 report giving error when refreshing dataset 

### ISSUE THREAD

**Issue by kine** [microsoft/BCTech#218]
I have updated our BI app "Dynamics 365 Business Central Usage" to v357 and when refreshing the dataset, I am getting this error:

```
Data source error: Column 'ObjectHash' in Table 'ObjectDim' contains a duplicate value 'b21d1c2fb7ad8af0e789596a51eb4016' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: ObjectDim.
Cluster URI: WABI-NORTH-EUROPE-redirect.analysis.windows.net
Activity ID: 1c6364e2-878a-484c-b35d-d4da463a6efe
Request ID: e983e639-065a-21ae-7c9c-e473999efd86
Time: 2023-11-06 14:09:42Z
```

**Comment by KennieNP** [comment]
Found the bug. Will push a new version of the app now. 

Try the beta here:

aka.ms/bctelemetryreportbeta

**Comment by HilmarVilhjalmsson** [comment]
Hi @KennieNP, this June I started to get the same error as initially reported in this ticket.  I have installed the latest version of the PowerBI app but still the same error


Dataset has failed to refresh.
Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support.

Column '<oii>ObjectHash</oii>' in Table '<oii>ObjectDim</oii>' contains a duplicate value '<ccon>05465d1f9382eaae8fff8808a0fb0eb2</ccon>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: ObjectDim.

Next refresh for Dataset is scheduled for July 3, 2025 0:00 UTC.
Technical Information
Activity Id: c5561536-db94-4fa6-a82f-1e49aebc63c3
Request Id: 6a4969b8-bdd0-4609-88b9-e1da035575e8
Cluster Name: WABI-NORTH-EUROPE-J-PRIMARY-redirect.analysis.windows.net
Refresh Start Time: July 2, 2025 0:01 UTC
Refresh End Time: July 2, 2025 0:11 UTC

**Comment by HilmarVilhjalmsson** [comment]
> Hi [@KennieNP](https://github.com/KennieNP), this June I started to get the same error as initially reported in this ticket. I have installed the latest version of the PowerBI app but still the same error
> 
> Dataset has failed to refresh. Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support.
> 
> Column 'ObjectHash' in Table 'ObjectDim' contains a duplicate value '05465d1f9382eaae8fff8808a0fb0eb2' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: ObjectDim.
> 
> Next refresh for Dataset is scheduled for July 3, 2025 0:00 UTC. Technical Information Activity Id: c5561536-db94-4fa6-a82f-1e49aebc63c3 Request Id: 6a4969b8-bdd0-4609-88b9-e1da035575e8 Cluster Name: WABI-NORTH-EUROPE-J-PRIMARY-redirect.analysis.windows.net Refresh Start Time: July 2, 2025 0:01 UTC Refresh End Time: July 2, 2025 0:11 UTC

Dataset was updated successfully last night :-)
