### ISSUE TITLE
PartnerCenter.ps1 : Error MFA required

### ISSUE THREAD

**Issue by pmatsconsulting** [microsoft/BCTech#34]
Try to run PartnerCenter.ps1

Getting error : 
```
AVERTISSEMENT : Attempting to launch a browser for authorization code login.
AVERTISSEMENT : We have launched a browser for you to login. For the old experience with device code flow, please run 'Connect-PartnerCenter -UseDeviceAuthentication'.

Account                                  Environment                                      TenantId                                        
-------                                  -----------                                      --------                                        
a5da473b-298e-43ac-aeee-10464b8c8d50     AzureCloud                                       b2e5620f-08f0-4196-857b-023ebf400b7c            
Get-PartnerCustomer : Authentication failed. MFA required. (10001)
Au caractère Ligne:14 : 14
+ $customers = Get-PartnerCustomer
+              ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [Get-PartnerCustomer], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomer
```

**Comment by chrishdmicrosoftcom** [comment]
I cannot reproduce this.

It looks like the following happens:
 1. You authenticate without MFA
 2. When you call Partner Center APIs, you get rejected because you didn't authenticate with MFA

This could be explained by a setup in your AAD tenant where you haven't enabled MFA on your user, but the Partner Center APIs do require MFA.

By policy, all Partner Center accounts must be enabled for MFA, so could you try to enable MFA and see if that helps? The way you do that is by going to the Azure portal, click Azure Active Directory, click Users, click the "Multi-Factor Authentication" button. And then enable your user if it isn't already.
